# side length of the chessboard squares in m
# double
checkerboard_cell_size: 0.03

# number of checkerboard calibration points (in x- and y-direction), i.e. those points where 4 squares meet
# vector<double>
checkerboard_pattern_size: [x,y]

# name of detected checkerboard frame
# string
checkerboard_frame: "checkerboard_detected"

# name of camera frame (on which the image is based on)
# string
camera_frame: ""

# image topic, raw format (not rectified)
# string
camera_image_raw_topic: ""

# topic to retrieve the intrinsic parameters from
# string
camera_info_topic: ""

# number of distortion parameters of the camera model, min: 0
# int
number_distortion_parameters: 5

# update frequency (has to be positive) at which the detection will be tried to loop at [in Hz]
# double
update_frequency: 10

# defines how much (in percent) of the freshly detected transform will be used to update the tf checkerboard transform. range: [0.1, 1.0]
# double
update_percentage: 0.8
